name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          mvn clean package -f order-service/pom.xml
          mvn clean package -f inventory-service/pom.xml
          mvn clean package -f payment-service/pom.xml
          mvn clean package -f config-server/pom.xml
